artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rithinprem/Datasets-for-ML/raw/main/Flight_Data.xlsx
  local_data_file: artifacts/data_ingestion/data.xlsx

data_validation :
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data.xlsx
  STATUS_FILE: artifacts/data_validation/status.txt
